### ISSUE TITLE
Compile on change

### ISSUE THREAD

**Issue by TheMaaarc** [frontend-workflow-cloud-compiler/client#3]
I know that we don't know which `scss` file is required for which `unglue` file.

But we could:
* Compile `scss` on change of a `scss` file
* Compile the correct `js` unglue file (we know which js file is loaded in which unglue file)
* Compile `svg` only when one of the `svg` files changed

And we need to write somewhere that new files will only be recognised when you restart the client. Right?

**Comment by nadar** [comment]
Done. Except of svg as this implementation is currently missing at all.
