### ISSUE TITLE
Unglue client css request even if css key not given in config

### ISSUE THREAD

**Issue by TheMaaarc** [frontend-workflow-cloud-compiler/client#5]
## Unglue config:

```json
{
    "js": [
        "../src/js/accordion.js"
    ]
}
```
## Expected:

The client compiles js and is done.

## Result:

The client compiles js and then tries to compile css (but because no files are given (mainFiles) the server returns an error).

![screenshot 2019-01-02 at 15 59 29](https://user-images.githubusercontent.com/3450438/50597523-f25cb500-0ea7-11e9-9ff4-3ea49d837e6e.png)

**Comment by nadar** [comment]
@TheMaaarc I just releases version 1.0.1, run composer update and the behavior should be as expected. Thanks for the report.
